--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 17.2 (Ubuntu 17.2-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account (
    "accountID" integer NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    "phoneNumber" character varying(10),
    email character varying(255) NOT NULL,
    "fullName" character varying(255) NOT NULL,
    gender boolean NOT NULL,
    avatar text,
    status boolean NOT NULL,
    role boolean NOT NULL,
    "emailVerified" boolean DEFAULT false NOT NULL
);


--
-- Name: Account_accountID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account ALTER COLUMN "accountID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Account_accountID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.address (
    "addressID" integer NOT NULL,
    "phoneNumber" character varying(10) NOT NULL,
    "fullName" character varying(255) NOT NULL,
    address character varying(255) NOT NULL,
    "specificAddress" character(255) NOT NULL,
    status boolean DEFAULT false NOT NULL,
    "provinceID" integer NOT NULL,
    "districtID" integer NOT NULL,
    "wardID" integer NOT NULL,
    "deleteStatus" boolean NOT NULL,
    "accountID" integer NOT NULL,
    "wardCode" character varying(10) NOT NULL
);


--
-- Name: Address_addressID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.address ALTER COLUMN "addressID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Address_addressID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_detail (
    "cartID" integer NOT NULL,
    quantity integer NOT NULL,
    "productID" integer NOT NULL,
    "accountID" integer NOT NULL
);


--
-- Name: CartDetail_cartID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_detail ALTER COLUMN "cartID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."CartDetail_cartID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoice_detail (
    "invoiceDetailID" integer NOT NULL,
    quantity integer NOT NULL,
    price real NOT NULL,
    "productID" integer NOT NULL,
    "invoiceID" integer NOT NULL
);


--
-- Name: InvoiceDetail_invoiceDetailID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.invoice_detail ALTER COLUMN "invoiceDetailID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."InvoiceDetail_invoiceDetailID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoice_status (
    "invoiceStatusID" integer NOT NULL,
    "statusName" character varying(100) NOT NULL
);


--
-- Name: InvoiceStatus_invoiceStatusID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.invoice_status ALTER COLUMN "invoiceStatusID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."InvoiceStatus_invoiceStatusID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoice (
    "invoiceID" integer NOT NULL,
    "shippingFee" real NOT NULL,
    "totalPrice" real NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "paymentMethod" boolean NOT NULL,
    status boolean NOT NULL,
    note character varying(255),
    "cancelReason" character varying(255),
    "receiveAddress" character varying(200) NOT NULL,
    "receiveName" character varying(100) NOT NULL,
    "receivePhone" character varying(10) NOT NULL,
    "accountID" integer NOT NULL,
    "invoiceStatusID" integer NOT NULL
);


--
-- Name: Invoice_invoiceID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.invoice ALTER COLUMN "invoiceID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Invoice_invoiceID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_images (
    "productImageID" integer NOT NULL,
    image character varying(255) NOT NULL,
    "productID" integer NOT NULL
);


--
-- Name: ProductImages_produtImageID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_images ALTER COLUMN "productImageID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductImages_produtImageID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_type (
    "productTypeID" integer NOT NULL,
    "typeName" character varying(255) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: ProductType_productTypeID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_type ALTER COLUMN "productTypeID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."ProductType_productTypeID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product (
    "productID" integer NOT NULL,
    "productName" character varying(255) NOT NULL,
    price real NOT NULL,
    "coverImage" character varying(255) NOT NULL,
    description character varying(255),
    status boolean NOT NULL,
    "insertDate" date NOT NULL,
    "productTypeID" integer NOT NULL,
    weight real NOT NULL
);


--
-- Name: Product_productID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product ALTER COLUMN "productID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Product_productID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: province; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.province (
    "provinceID" integer NOT NULL,
    "provinceCode" integer NOT NULL,
    "provinceName" character varying(100) NOT NULL
);


--
-- Name: Province_provinceID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.province ALTER COLUMN "provinceID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Province_provinceID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reply; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reply (
    "replyID" integer NOT NULL,
    reply character varying(255) NOT NULL,
    "isReplied" boolean NOT NULL,
    "reviewID" integer NOT NULL,
    "accountID" integer NOT NULL
);


--
-- Name: Reply_replyID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reply ALTER COLUMN "replyID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Reply_replyID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_images (
    "reviewImageID" integer NOT NULL,
    "imageName" character varying(200) NOT NULL,
    "reviewID" integer NOT NULL
);


--
-- Name: ReviewImages_reviewImageID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review_images ALTER COLUMN "reviewImageID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."ReviewImages_reviewImageID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review (
    "reviewID" integer NOT NULL,
    "reviewDate" timestamp without time zone NOT NULL,
    stars integer NOT NULL,
    comment character varying(255) NOT NULL,
    status boolean NOT NULL,
    "productID" integer NOT NULL,
    "accountID" integer NOT NULL,
    "invoiceID" integer NOT NULL
);


--
-- Name: Review_reviewID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review ALTER COLUMN "reviewID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Review_reviewID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction (
    "transactionID" integer NOT NULL,
    "transactionCode" character varying(255) NOT NULL,
    "cardNumber" character varying(100) NOT NULL,
    "fullName" character varying(100) NOT NULL,
    "transactionDate" date NOT NULL,
    status boolean NOT NULL,
    amount real NOT NULL,
    "accountID" integer NOT NULL,
    "invoiceID" integer NOT NULL
);


--
-- Name: Transaction_transactionID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transaction ALTER COLUMN "transactionID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Transaction_transactionID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: district; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.district (
    "districtID" integer NOT NULL,
    "districtCode" integer NOT NULL,
    "districtName" character varying(100) NOT NULL,
    "provinceID" integer NOT NULL
);


--
-- Name: Ward_wardID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.district ALTER COLUMN "districtID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Ward_wardID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ward; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ward (
    "wardID" integer NOT NULL,
    "wardCode" integer NOT NULL,
    "wardName" character varying(100) NOT NULL,
    "districtID" integer NOT NULL
);


--
-- Name: Ward_wardID_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ward ALTER COLUMN "wardID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Ward_wardID_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oauth_account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oauth_account (
    "oauthID" integer NOT NULL,
    "accountID" integer NOT NULL,
    provider text NOT NULL,
    "providerUserID" text NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now()
);


--
-- Name: oauth_account_oauthID_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."oauth_account_oauthID_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: oauth_account_oauthID_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."oauth_account_oauthID_seq" OWNED BY public.oauth_account."oauthID";


--
-- Name: oauth_account oauthID; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_account ALTER COLUMN "oauthID" SET DEFAULT nextval('public."oauth_account_oauthID_seq"'::regclass);


--
-- Name: account Account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT "Account_pkey" PRIMARY KEY ("accountID");


--
-- Name: address Address_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT "Address_pkey" PRIMARY KEY ("addressID");


--
-- Name: cart_detail CartDetail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_detail
    ADD CONSTRAINT "CartDetail_pkey" PRIMARY KEY ("cartID");


--
-- Name: invoice_detail InvoiceDetail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_detail
    ADD CONSTRAINT "InvoiceDetail_pkey" PRIMARY KEY ("invoiceDetailID");


--
-- Name: invoice_status InvoiceStatus_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_status
    ADD CONSTRAINT "InvoiceStatus_pkey" PRIMARY KEY ("invoiceStatusID");


--
-- Name: invoice Invoice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT "Invoice_pkey" PRIMARY KEY ("invoiceID");


--
-- Name: product_images ProductImages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT "ProductImages_pkey" PRIMARY KEY ("productImageID");


--
-- Name: product_type ProductType_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_type
    ADD CONSTRAINT "ProductType_pkey" PRIMARY KEY ("productTypeID");


--
-- Name: product Product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT "Product_pkey" PRIMARY KEY ("productID");


--
-- Name: province Province_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.province
    ADD CONSTRAINT "Province_pkey" PRIMARY KEY ("provinceID");


--
-- Name: reply Reply_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reply
    ADD CONSTRAINT "Reply_pkey" PRIMARY KEY ("replyID");


--
-- Name: review_images ReviewImages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_images
    ADD CONSTRAINT "ReviewImages_pkey" PRIMARY KEY ("reviewImageID");


--
-- Name: review Review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT "Review_pkey" PRIMARY KEY ("reviewID");


--
-- Name: transaction Transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT "Transaction_pkey" PRIMARY KEY ("transactionID");


--
-- Name: district Ward_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.district
    ADD CONSTRAINT "Ward_pkey" PRIMARY KEY ("districtID");


--
-- Name: ward Ward_pkey1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ward
    ADD CONSTRAINT "Ward_pkey1" PRIMARY KEY ("wardID");


--
-- Name: account email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT email UNIQUE (email);


--
-- Name: oauth_account oauth_account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_account
    ADD CONSTRAINT oauth_account_pkey PRIMARY KEY ("oauthID");


--
-- Name: oauth_account oauth_account_provider_providerUserID_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_account
    ADD CONSTRAINT "oauth_account_provider_providerUserID_key" UNIQUE (provider, "providerUserID");


--
-- Name: account phoneNumber; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT "phoneNumber" UNIQUE ("phoneNumber");


--
-- Name: product_type typeName_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_type
    ADD CONSTRAINT "typeName_unique" UNIQUE ("typeName");


--
-- Name: cart_detail FK_CartDetail_Account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_detail
    ADD CONSTRAINT "FK_CartDetail_Account" FOREIGN KEY ("accountID") REFERENCES public.account("accountID") NOT VALID;


--
-- Name: cart_detail FK_CartDetail_Product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_detail
    ADD CONSTRAINT "FK_CartDetail_Product" FOREIGN KEY ("productID") REFERENCES public.product("productID") NOT VALID;


--
-- Name: district FK_District_Province; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.district
    ADD CONSTRAINT "FK_District_Province" FOREIGN KEY ("provinceID") REFERENCES public.province("provinceID") NOT VALID;


--
-- Name: invoice_detail FK_InvoiceDetail_Invoice; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_detail
    ADD CONSTRAINT "FK_InvoiceDetail_Invoice" FOREIGN KEY ("invoiceID") REFERENCES public.invoice("invoiceID") NOT VALID;


--
-- Name: invoice_detail FK_InvoiceDetail_Product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_detail
    ADD CONSTRAINT "FK_InvoiceDetail_Product" FOREIGN KEY ("productID") REFERENCES public.product("productID") NOT VALID;


--
-- Name: invoice FK_Invoice_Account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT "FK_Invoice_Account" FOREIGN KEY ("accountID") REFERENCES public.account("accountID") NOT VALID;


--
-- Name: invoice FK_Invoice_InvoiceStatus; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT "FK_Invoice_InvoiceStatus" FOREIGN KEY ("invoiceStatusID") REFERENCES public.invoice_status("invoiceStatusID") NOT VALID;


--
-- Name: product_images FK_ProductImages_Product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT "FK_ProductImages_Product" FOREIGN KEY ("productID") REFERENCES public.product("productID") NOT VALID;


--
-- Name: product FK_Product_ProductType; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT "FK_Product_ProductType" FOREIGN KEY ("productTypeID") REFERENCES public.product_type("productTypeID") NOT VALID;


--
-- Name: reply FK_Reply_Account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reply
    ADD CONSTRAINT "FK_Reply_Account" FOREIGN KEY ("accountID") REFERENCES public.account("accountID") NOT VALID;


--
-- Name: reply FK_Reply_Review; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reply
    ADD CONSTRAINT "FK_Reply_Review" FOREIGN KEY ("reviewID") REFERENCES public.review("reviewID") NOT VALID;


--
-- Name: review_images FK_ReviewImages_Review; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_images
    ADD CONSTRAINT "FK_ReviewImages_Review" FOREIGN KEY ("reviewID") REFERENCES public.review("reviewID") NOT VALID;


--
-- Name: review FK_Review_Account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT "FK_Review_Account" FOREIGN KEY ("accountID") REFERENCES public.account("accountID") NOT VALID;


--
-- Name: review FK_Review_Invoice; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT "FK_Review_Invoice" FOREIGN KEY ("invoiceID") REFERENCES public.invoice("invoiceID") NOT VALID;


--
-- Name: review FK_Review_Product; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT "FK_Review_Product" FOREIGN KEY ("productID") REFERENCES public.product("productID") NOT VALID;


--
-- Name: transaction FK_Transaction_Account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT "FK_Transaction_Account" FOREIGN KEY ("accountID") REFERENCES public.account("accountID") NOT VALID;


--
-- Name: transaction FK_Transaction_Invoice; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT "FK_Transaction_Invoice" FOREIGN KEY ("invoiceID") REFERENCES public.invoice("invoiceID") NOT VALID;


--
-- Name: ward FK_Ward_District; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ward
    ADD CONSTRAINT "FK_Ward_District" FOREIGN KEY ("districtID") REFERENCES public.district("districtID") NOT VALID;


--
-- Name: address FK_address_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT "FK_address_account" FOREIGN KEY ("accountID") REFERENCES public.account("accountID") NOT VALID;


--
-- Name: oauth_account oauth_account_accountID_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oauth_account
    ADD CONSTRAINT "oauth_account_accountID_fkey" FOREIGN KEY ("accountID") REFERENCES public.account("accountID");


--
-- PostgreSQL database dump complete
--

