name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: DB_CONNECTION   # gắn job này với environment DB_CONNECTION
    defaults:
      run:
        working-directory: GoodFood-BE

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ vars.DB_USER }}
          POSTGRES_PASSWORD: ${{ vars.DB_PASSWORD }}
          POSTGRES_DB: ${{ vars.DB_NAME }}
        options: >-
          --health-cmd="pg_isready -U ${{ vars.DB_USER }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.6'
          cache: true

      - name: Download dependencies
        run: go mod tidy

      - name: Wait for DB ready
        run: |
          until pg_isready -h localhost -p 5432 -U $DB_USER; do
            echo "Waiting for postgres..."
            sleep 2
          done
        env:
          DB_USER: ${{ vars.DB_USER }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: ${{ vars.DB_USER }}
          DB_PASSWORD: ${{ vars.DB_PASSWORD }}
          DB_NAME: ${{ vars.DB_NAME }}
