name: Go with TFLite C API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.6'

      # Cache TensorFlow Lite C API
      - name: Cache TensorFlow Lite C API
        id: cache-tflite
        uses: actions/cache@v3
        with:
          path: /usr/local/tflite_c
          key: ${{ runner.os }}-tflite-c-api-v2.12.0

      # Install TFLite C API if not cached
      - name: Install TensorFlow Lite C API
        if: steps.cache-tflite.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/tensorflow/tensorflow/releases/download/v2.12.0/libtensorflowlite_c-linux-x86_64-2.12.0.tar.gz
          mkdir tflite_c
          tar -xzf libtensorflowlite_c-linux-x86_64-2.12.0.tar.gz -C tflite_c
          sudo mkdir -p /usr/local/tflite_c
          sudo cp -r tflite_c/* /usr/local/tflite_c/
          sudo ldconfig

      # Set env for CGO
      - name: Configure TensorFlow Lite C API paths
        run: |
          echo "CGO_CFLAGS=-I/usr/local/tflite_c/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L/usr/local/tflite_c/lib -ltensorflowlite_c" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/tflite_c/lib" >> $GITHUB_ENV

      - name: Build
        run: go build -v ./...
        working-directory: GoodFood-BE

      - name: Test
        run: go test -v ./...
        working-directory: GoodFood-BE
