name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.6'

      # Install prebuilt TensorFlow Lite C API
      - name: Install TensorFlow Lite C API
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.14.0.zip
          unzip v2.14.0.zip
          cd tensorflow-2.14.0/tensorflow/lite/c
          cmake .
          make -j$(nproc)
          sudo cp libtensorflowlite_c.so /usr/local/lib/
          sudo mkdir -p /usr/local/include/tensorflow/lite/c
          sudo cp c_api*.h /usr/local/include/tensorflow/lite/c/
          sudo ldconfig

      - name: Build
        run: go build -v ./...
        working-directory: GoodFood-BE

      - name: Test
        run: go test -v ./...
        working-directory: GoodFood-BE
