name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DB_CONNECTION
    defaults:
      run:
        working-directory: GoodFood-BE

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.6'
          cache: true

      - name: Download dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      # Chạy test, bỏ qua auto-gen boil tests
      - name: Run tests (exclude sqlboiler auto-gen)
        run: go test -v ./... -tags '!boiltests'
