name: Go with TFLite C API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.6'

      # Cache TFLite C API installation
      - name: Cache TensorFlow C API
        id: cache-tflite
        uses: actions/cache@v3
        with:
          path: /usr/local/tensorflow_c
          key: ${{ runner.os }}-tf-c-api-v2.18.0

      # Install if not cached
      - name: Install TensorFlow C API
        if: steps.cache-tflite.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://storage.googleapis.com/tensorflow/versions/2.18.0/libtensorflow-cpu-linux-x86_64.tar.gz
          mkdir tf_c
          tar -xzf libtensorflow-cpu-linux-x86_64.tar.gz -C tf_c
          sudo mkdir -p /usr/local/tensorflow_c
          sudo cp -r tf_c/* /usr/local/tensorflow_c/
          sudo ldconfig

      # Set environment for cgo to find headers/libs
      - name: Configure TensorFlow C API paths
        run: |
          echo "C_INCLUDE_PATH=/usr/local/tensorflow_c/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=/usr/local/tensorflow_c/lib" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/tensorflow_c/lib" >> $GITHUB_ENV

      - name: Build
        run: go build -v ./...
        working-directory: GoodFood-BE

      - name: Test
        run: go test -v ./...
        working-directory: GoodFood-BE
