name: Go CI with TFLite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: GoodFood-BE

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Prepare TensorFlow Lite libs & headers
        run: |
          # Tạo thư mục cho lib và include
          sudo mkdir -p /usr/local/tflite/lib
          sudo mkdir -p /usr/local/tflite/include/tensorflow/lite/c

          # Copy các file .so
          sudo cp ./libs/libtensorflowlite.so /usr/local/tflite/lib/
          sudo cp ./libs/libtensorflowlite_c.so /usr/local/tflite/lib/

          # Copy header c_api.h
          sudo cp ./libs/c_api.h /usr/local/tflite/include/tensorflow/lite/c/

          # Thiết lập env cho CGO
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I/usr/local/tflite/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L/usr/local/tflite/lib -ltensorflowlite -ltensorflowlite_c" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/tflite/lib:\$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
